language: php
git:
  depth: 10
php:
  - 5.6
before_install:
  - composer self-update
install:
  - composer install --no-interaction
before_script:
  - cp .env.example .env
  - php artisan key:generate
  - touch database/database.sqlite
  - php artisan migrate
script:
  - vendor/bin/phpunit
matrix:
  fast_finish: true
branches:
  only:
    - master